[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "../node_modules"]
allow_paths = ["../node_modules"]
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read-write", path = "./deployments" },
]
